name: build

env:
  VMTOOLS_PREFIX: /opt/VirtualMetal/vmtools
  VMTOOLS_BINUTILS: binutils-2.39
  VMTOOLS_GCC: gcc-12.2.0
  VMTOOLS_GDB: gdb-12.1

on:
  push:
    branches:
      # build on all branches except master
      - '*'
      - '!master'
    tags:
      # build on release tags only
      - 'r[0-9]+'
  workflow_dispatch:

jobs:

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        target: [x86_64-elf, aarch64-elf]
        include:
          - os: windows-latest
            shell: msys2 {0}
          - os: ubuntu-latest
            shell: bash
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install prerequisites (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-expat
      - name: Install prerequisites (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt install libgmp3-dev
          sudo apt install libmpc-dev
          sudo apt install libmpfr-dev
          sudo apt install libisl-dev
          sudo apt install libexpat-dev
      - name: Download binutils source
        run: |
          wget -q https://ftp.gnu.org/gnu/binutils/$VMTOOLS_BINUTILS.tar.xz
          tar xf $VMTOOLS_BINUTILS.tar.xz
      - name: Download gcc source
        run: |
          wget -q https://ftp.gnu.org/gnu/gcc/$VMTOOLS_GCC/$VMTOOLS_GCC.tar.xz
          tar xf $VMTOOLS_GCC.tar.xz
      - name: Download gdb source
        run: |
          wget -q https://ftp.gnu.org/gnu/gdb/$VMTOOLS_GDB.tar.xz
          tar xf $VMTOOLS_GDB.tar.xz
      - name: Prepare environment
        run: |
          VMTOOLS_HOST=$($VMTOOLS_BINUTILS/config.guess | cut -d- -f1,3-)
          VMTOOLS_TARGET=${{ matrix.target }}
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VMTOOLS_RELEASE=${{ github.ref_name }}
          else
            VMTOOLS_RELEASE="dev$(date +%y%j)"
          fi
          echo VMTOOLS_HOST=$VMTOOLS_HOST
          echo VMTOOLS_TARGET=$VMTOOLS_TARGET
          echo VMTOOLS_RELEASE=$VMTOOLS_RELEASE
          echo VMTOOLS_HOST=$VMTOOLS_HOST >>$GITHUB_ENV
          echo VMTOOLS_TARGET=$VMTOOLS_TARGET >>$GITHUB_ENV
          echo VMTOOLS_RELEASE=$VMTOOLS_RELEASE >>$GITHUB_ENV
      - name: Build binutils
        run: |
          mkdir -p build/$VMTOOLS_BINUTILS && cd build/$VMTOOLS_BINUTILS
          ../../$VMTOOLS_BINUTILS/configure \
              --prefix=$VMTOOLS_PREFIX/host.$VMTOOLS_HOST \
              --target=$VMTOOLS_TARGET \
              --with-sysroot \
              --disable-plugins \
              --disable-lto \
              --disable-nls \
              LDFLAGS=--static
          make -j4
          make install-strip DESTDIR=$(pwd)/../dist
          make install-strip
      - name: Build gcc
        run: |
          export PATH="$VMTOOLS_PREFIX/host.$VMTOOLS_HOST/bin:$PATH"
          mkdir -p build/$VMTOOLS_GCC && cd build/$VMTOOLS_GCC
          ../../$VMTOOLS_GCC/configure \
              --prefix=$VMTOOLS_PREFIX/host.$VMTOOLS_HOST \
              --target=$VMTOOLS_TARGET \
              --enable-languages=c \
              --without-headers \
              --disable-plugins \
              --disable-lto \
              --disable-nls \
              LDFLAGS=--static
          make -j4 all-gcc
          make -j4 all-target-libgcc
          make install-strip-gcc DESTDIR=$(pwd)/../dist
          make install-strip-target-libgcc DESTDIR=$(pwd)/../dist
      - name: Build gdb
        run: |
          export PATH="$VMTOOLS_PREFIX/host.$VMTOOLS_HOST/bin:$PATH"
          mkdir -p build/$VMTOOLS_GDB && cd build/$VMTOOLS_GDB
          ../../$VMTOOLS_GDB/configure \
              --prefix=$VMTOOLS_PREFIX/host.$VMTOOLS_HOST \
              --target=$VMTOOLS_TARGET \
              --with-expat \
              --without-python \
              --without-guile \
              --disable-sim \
              --disable-plugins \
              --disable-lto \
              --disable-nls \
              LDFLAGS=--static
          make -j4 all-gdb
          make install-strip-gdb DESTDIR=$(pwd)/../dist
      - name: Package vmtools
        run: |
          cd build/dist
          rm -rf $VMTOOLS_PREFIX/host.$VMTOOLS_HOST/share/{info,man}
          tar cf - opt | xz -9 >vmtools-$VMTOOLS_GCC-$VMTOOLS_RELEASE+$VMTOOLS_HOST+$VMTOOLS_TARGET.tar.xz
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vmtools
          path: |
            build/dist/vmtools*.tar.xz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Prepare environment
        run: |
          VMTOOLS_RELEASE=${{ github.ref_name }}
          echo VMTOOLS_RELEASE=$VMTOOLS_RELEASE
          echo VMTOOLS_RELEASE=$VMTOOLS_RELEASE >>$GITHUB_ENV
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: vmtools
      - name: Package vmtools
        run: |
          for f in vmtools*.tar.xz; do tar xf $f; done
          tar cf - opt | xz -9 >vmtools-$VMTOOLS_GCC-$VMTOOLS_RELEASE.tar.xz
      - name: Release ${{ github.ref_name }}
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            Included tools:
            - ${{ env.VMTOOLS_GCC }}
            - ${{ env.VMTOOLS_GDB }}
            - ${{ env.VMTOOLS_BINUTILS }}
          files: vmtools*.tar.xz
